#Configuracion de la base de datos
#Valores de prueba en desarrollo que sólo funcona en localhost
#cuando pasemo da produccción, en el servidor real, modificaremos
#la calse Conexion para que en lugar de buscar texto plano
#busque Varibales d eEntorno del sistema operativo.
bd.url=jdbc:mysql://localhost:3306/colegio
bd.usuario=admin_colegio
bd.clave=colegio1234